"""add snippets table

Revision ID: a9bde3475de8
Revises: 1cfac75772f1
Create Date: 2026-07-28 23:00:48.884200
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'a9bde3475de8'
down_revision: Union[str, None] = '1cfac75772f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('snippets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nome', sa.String(length=120), nullable=False),
    sa.Column('atalho', sa.String(length=40), nullable=False),
    sa.Column('conteudo', sa.Text(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'atalho', name='uq_snippet_tenant_atalho')
    )
    op.create_index(op.f('ix_snippets_tenant_id'), 'snippets', ['tenant_id'], unique=False)
    # ### end Alembic commands ###
    # Nota: o autogenerate também detectou remoção de 5 índices compostos em
    # companies/deals/tasks/timeline_events (drift entre migrações antigas e os
    # modelos atuais, pré-existente e sem relação com snippets) — removidos
    # deste arquivo intencionalmente para não tocar em índices de outras tabelas.


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_snippets_tenant_id'), table_name='snippets')
    op.drop_table('snippets')
    # ### end Alembic commands ###
