"""add lead_prospects

Revision ID: fcf64430cfe5
Revises: c74b9d66990a
Create Date: 2026-07-28 17:26:35.614750
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'fcf64430cfe5'
down_revision: Union[str, None] = 'c74b9d66990a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lead_prospects',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('empresa', sa.String(length=255), nullable=False),
    sa.Column('setor', sa.String(length=80), nullable=True),
    sa.Column('segmento', sa.String(length=120), nullable=True),
    sa.Column('uf', sa.String(length=2), nullable=True),
    sa.Column('faixa_funcionarios', sa.String(length=20), nullable=True),
    sa.Column('faturamento', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('site', sa.String(length=255), nullable=True),
    sa.Column('telefone', sa.String(length=20), nullable=True),
    sa.Column('linkedin', sa.String(length=255), nullable=True),
    sa.Column('dor_sugerida', sa.Text(), nullable=True),
    sa.Column('contato_sugerido', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('pesquisado_por', sa.UUID(), nullable=False),
    sa.Column('promoted_company_id', sa.UUID(), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['pesquisado_por'], ['users.id'], ),
    sa.ForeignKeyConstraint(['promoted_company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lead_prospects_empresa'), 'lead_prospects', ['empresa'], unique=False)
    op.create_index(op.f('ix_lead_prospects_pesquisado_por'), 'lead_prospects', ['pesquisado_por'], unique=False)
    op.create_index(op.f('ix_lead_prospects_status'), 'lead_prospects', ['status'], unique=False)
    op.create_index(op.f('ix_lead_prospects_tenant_id'), 'lead_prospects', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_lead_prospects_tenant_id'), table_name='lead_prospects')
    op.drop_index(op.f('ix_lead_prospects_status'), table_name='lead_prospects')
    op.drop_index(op.f('ix_lead_prospects_pesquisado_por'), table_name='lead_prospects')
    op.drop_index(op.f('ix_lead_prospects_empresa'), table_name='lead_prospects')
    op.drop_table('lead_prospects')
    # ### end Alembic commands ###
